package com.hugh.memorandum.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hugh.memorandum.bean.Memo;

import com.hugh.memorandum.greendao.MemoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoDaoConfig;

    private final MemoDao memoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoDaoConfig = daoConfigMap.get(MemoDao.class).clone();
        memoDaoConfig.initIdentityScope(type);

        memoDao = new MemoDao(memoDaoConfig, this);

        registerDao(Memo.class, memoDao);
    }
    
    public void clear() {
        memoDaoConfig.clearIdentityScope();
    }

    public MemoDao getMemoDao() {
        return memoDao;
    }

}
